-- 既存のテーブルを全て削除（クリーンアップ）
-- 注意: 本番環境では慎重に実行してください

DROP TABLE IF EXISTS announcements CASCADE;
DROP TABLE IF EXISTS split_times CASCADE;
DROP TABLE IF EXISTS race_feedbacks CASCADE;
DROP TABLE IF EXISTS milestone_reviews CASCADE;
DROP TABLE IF EXISTS milestones CASCADE;
DROP TABLE IF EXISTS race_reviews CASCADE;
DROP TABLE IF EXISTS race_goals CASCADE;
DROP TABLE IF EXISTS objectives CASCADE;
DROP TABLE IF EXISTS practice_times CASCADE;
DROP TABLE IF EXISTS practice_logs CASCADE;
DROP TABLE IF EXISTS entries CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS records CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS styles CASCADE;
DROP TABLE IF EXISTS user_sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
