name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          **/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate GraphQL types
      run: npm run graphql:codegen
    
    - name: Lint
      run: npm run lint
      env:
        CI: true
    
    - name: Type check
      run: npm run type-check
  
  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate GraphQL types
      run: npm run graphql:codegen
    
    - name: Build web app
      run: npm run build:web
  
  build-packages:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate GraphQL types
      run: npm run graphql:codegen
    
    - name: Build types package
      run: npm run build --workspace=packages/types
    
    - name: Build GraphQL schema package
      run: npm run build --workspace=packages/graphql-schema
