name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          **/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build web app
      run: npm run build:web
    
    # Vercel, Netlify, または他のホスティングサービスへのデプロイ設定
    # 例: Vercel
    # - name: Deploy to Vercel
    #   uses: amondnet/vercel-action@v25
    #   with:
    #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
    #     vercel-org-id: ${{ secrets.ORG_ID }}
    #     vercel-project-id: ${{ secrets.PROJECT_ID }}
    #     working-directory: ./apps/web
  
  deploy-supabase:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
    
    # Supabase Edge Functionsのデプロイ
    # - name: Deploy Supabase Functions
    #   run: |
    #     supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
    #   env:
    #     SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    #   working-directory: ./apps/supabase
